targets_eval:
  - stl1
  - stl2
  - stl3


path_to_plots:  '../plots/'
path_to_results: '../results/'

year: 2022
network:  'soil_TERENO_ISMN_2022.nc' #'soil_SMOSMANIA_ISMN_2022.nc' # 'soil_TERENO_ISMN_2022.nc'
station: 'Gevenich' # 'Lahas'
variable: 'st'
depth: [0.05, 0.2, 0.5]
